// Content for Dr. Vishwas Sutar portfolio — bilingual (Marathi / English)
// Exposed as globals on `window` so pages work from file:// (no ES modules).

window.UI = {
  mr: {
    nav: { about: 'परिचय', music: 'संगीत', books: 'ग्रंथसंपदा', samajbhan: 'समाजभान', contact: 'संपर्क' },
    langBtn: 'EN',
    hero: {
      kicker: 'लेखक · गायक · संगीतकार · प्रशासकीय अधिकारी · समाजसेवक',
      name: 'डॉ. विश्वास सुतार',
      tagline: 'संगीत, शिक्षण, लेखन, व्याख्यान, नवोपक्रम आणि संशोधन अशा क्षेत्रांत सातत्याने सक्रिय',
      location: 'कोल्हापूर, महाराष्ट्र',
      phone: '९४२०३५३४५२',
      ctaBooks: 'पुस्तके पहा',
      ctaSamajbhan: 'समाजभान कार्य',
      badge: 'आकाशवाणी मान्यताप्राप्त गायक',
    },
    stats: [
      { num: '१२', label: 'प्रकाशित पुस्तके' },
      { num: '४६+', label: 'समाजभान उपक्रम' },
      { num: '१', label: 'नवा राग — विश्वतोडी' },
      { num: '१२+', label: 'पुरस्कार व सन्मान' },
    ],
    about: {
      title: 'परिचय',
      lead: 'डॉ. विश्वास सुतार, कोल्हापूर येथे संगीत, शिक्षण, लेखन, व्याख्यान, नवोपक्रम, संशोधन अशा विविध क्षेत्रांत सातत्याने सक्रिय आहेत. शिक्षण क्षेत्रात प्रशासकीय अधिकारी पदावर कार्यरत असून, त्यांनी ज्येष्ठ साहित्यिक डॉ. सुनीलकुमार लवटे यांच्या समग्र वाङ्मयावर पीएच.डी. प्राप्त केली आहे.',
      familyTitle: 'कौटुंबिक पार्श्वभूमी',
      family: 'आई-वडील अल्पशिक्षित. वडील सुतारकाम आणि बांधकाम व्यवसाय जमेल तसे करायचे; थोडीशीच शेती. आईच अधिक कष्ट करायची — पहाटे चारला उठून दिवसभर संसाराचा गाडा हाकायची. मुलांच्या शिक्षणाला आई-वडिलांनी प्राधान्य दिले. प्रसंगी शेतजमीन गहाण ठेवली, लोकांकडे हात पसरले, पण मुलांना शिकवले. दुष्काळाच्या पार्श्वभूमीवरील ऐंशीचे दशक मोठे खडतर होते.',
      eduTitle: 'शैक्षणिक वाटचाल',
      edu: 'प्राथमिक, माध्यमिक शिक्षण जन्मगाव शिरगाव येथे. शिक्षण पदविका (D.Ed.) पेटाळा, कोल्हापूर. महाविद्यालयीन शिक्षण भोगावती महाविद्यालय, कुरुकली. नोकरी करत असताना आचार्य जावडेकर महाविद्यालय, गारगोटी येथून B.Ed. आणि पुढे शिवाजी विद्यापीठातून डॉ. सुनीलकुमार लवटे यांच्या समग्र वाङ्मयावर पीएच.डी.',
      infoTitle: 'वैयक्तिक माहिती',
      info: [
        { k: 'पूर्ण नाव', v: 'डॉ. विश्वास इंदुबाई बंडू सुतार' },
        { k: 'जन्म', v: '२ जून १९७३ — शिरगाव, ता. राधानगरी, जि. कोल्हापूर' },
        { k: 'शिक्षण', v: 'एम.ए., बी.एड., पीएच.डी. (मराठी)' },
        { k: 'संगीत', v: 'संगीत विशारद (कंठ संगीत) — अखिल भारतीय गांधर्व महाविद्यालय, मिरज' },
        { k: 'कार्यरत', v: 'शिक्षण क्षेत्रात प्रशासकीय अधिकारी' },
      ],
      quote: 'प्रतिकूल परिस्थितीवर मात करत पुढे जाणे एवढेच हाती होते.',
      writingTitle: 'लेखन व साहित्य',
      writing: 'संवादी विचार, खलिलवाणी, मुलास पत्र या लेखमालांद्वारे सकारात्मक विचारांचा प्रसार. शिक्षक व नवोदित लेखक-कवींना लिहिते करण्यासाठी प्रोत्साहन व उपक्रमांचे आयोजन. लेखनात सामाजिक चिंतन आणि सकारात्मक बदलावर भर.',
      awardsTitle: 'पुरस्कार व सन्मान',
      awards: [
        'राजर्षी छत्रपती शाहू पुरस्कार — जिल्हा परिषद, कोल्हापूर',
        'स्वररत्न पुरस्कार — मायबोली प्रतिष्ठान, राधानगरी',
        'ग्रंथ पुरस्कार — संत गाडगे महाराज अध्यासन, कोल्हापूर',
        'विशेष साहित्य पुरस्कार — दक्षिण महाराष्ट्र साहित्य सभा, कोल्हापूर',
        'उत्कृष्ट चरित्र पुरस्कार — बालकुमार साहित्य सभा, कोल्हापूर',
        'समाजरत्न पुरस्कार — शहीद शिवाजी मगदूम प्रतिष्ठान, पिंपळगाव',
        'उत्कृष्ट साहित्य पुरस्कार — राजर्षी शाहू वाचनालय, थेरगाव',
        'साहित्य पुरस्कार — न्यूज गंगाधर, कोल्हापूर',
        'कै. नायब सुभेदार रंगराव देसाई राज्यस्तरीय साहित्य गौरव पुरस्कार — मिणचे खुर्द',
        'दर्पण पुरस्कार — कोल्हापूर',
        'कुशल प्रशासन अधिकारी सन्मान — शाहूवाडी तालुका शैक्षणिक व्यासपीठ',
        'आदर्श अधिकारी पुरस्कार — शिवम शैक्षणिक व सामाजिक संस्था, राशिवडे बु.',
      ],
    },
    music: {
      title: 'स्वरसाधना',
      kicker: 'संगीत',
      lead: 'आकाशवाणीचे मान्यताप्राप्त गायक. गायक, संगीतकार व मार्गदर्शक म्हणून विशेष ओळख.',
      ragaTitle: 'राग विश्वतोडी',
      raga: 'संगीत क्षेत्रात "विश्वतोडी" या नव्या रागाची निर्मिती — संगीत क्षेत्रातील एक महत्त्वाचा मानदंड.',
      airTitle: 'आकाशवाणी',
      air: 'आकाशवाणीचे मान्यताप्राप्त गायक म्हणून सादरीकरण.',
      visharadTitle: 'संगीत विशारद',
      visharad: 'कंठ संगीत — अखिल भारतीय गांधर्व महाविद्यालय, मिरज.',
      ytTitle: 'यूट्यूब वाहिनी',
      ytSub: 'संगीत आणि विचार — नवीन सादरीकरणे येथे पहा',
      ytBtn: 'वाहिनीला भेट द्या',
    },
    books: {
      title: 'ग्रंथसंपदा',
      kicker: 'प्रकाशित पुस्तके',
      lead: 'संविधान, संतसाहित्य, चरित्र, कथा आणि समीक्षा — विविध विषयांवरील बारा ग्रंथ.',
      featured: 'नवीन प्रकाशन',
      pages: 'पृष्ठे',
      price: 'किंमत',
      publisher: 'प्रकाशक',
      release: 'प्रकाशन',
      details: 'सविस्तर पहा',
      close: 'बंद करा',
      free: 'विनामूल्य वितरण',
      synopsis: 'ग्रंथाविषयी',
    },
    samajbhan: {
      title: 'समाजभान',
      kicker: 'सामाजिक कार्य',
      lead: 'वंचित, गरीब व गरजूंना मदतीचा हात देणाऱ्या "समाजभान" समुहाचे संकल्पक व कार्यकर्ते. २०१९ पासून आजतागायत ४६ हून अधिक उपक्रम.',
      mission: 'समाजातील वंचित, गरीब व गरजू लोकांना मदत करणे आणि त्यांच्या जीवनात सकारात्मक बदल आणणे हे आमचे मुख्य उद्दिष्ट.',
      timelineTitle: 'उपक्रमांची वाटचाल',
      readMore: 'अधिक वाचा',
      readLess: 'कमी करा',
      galleryTitle: 'छायाचित्र संग्रह',
      gallerySub: 'प्रत्यक्ष भेटी आणि वृत्तपत्र कात्रणे',
      all: 'सर्व',
    },
    contact: {
      title: 'संपर्क',
      lead: 'व्याख्याने, संगीत सादरीकरण, साहित्यिक उपक्रम किंवा समाजभान कार्याविषयी संपर्क साधा.',
      phone: 'दूरध्वनी',
      location: 'ठिकाण',
      locationV: 'कोल्हापूर, महाराष्ट्र',
      youtube: 'यूट्यूब',
      rights: 'सर्व हक्क राखीव',
    },
  },
  en: {
    nav: { about: 'About', music: 'Music', books: 'Books', samajbhan: 'Samajbhan', contact: 'Contact' },
    langBtn: 'मराठी',
    hero: {
      kicker: 'Author · Singer · Musician · Administrative Officer · Social Worker',
      name: 'Dr. Vishwas Sutar',
      tagline: 'Actively engaged in music, education, writing, lecturing, innovation and research',
      location: 'Kolhapur, Maharashtra',
      phone: '+91 94203 53452',
      ctaBooks: 'Explore Books',
      ctaSamajbhan: 'Samajbhan Work',
      badge: 'All India Radio approved singer',
    },
    stats: [
      { num: '12', label: 'Published Books' },
      { num: '46+', label: 'Samajbhan Initiatives' },
      { num: '1', label: 'New Raga — Vishwatodi' },
      { num: '12+', label: 'Awards & Honours' },
    ],
    about: {
      title: 'About',
      lead: 'Dr. Vishwas Sutar of Kolhapur is actively engaged in music, education, writing, lecturing, innovation and research. Serving as an Administrative Officer in the education sector, he earned his Ph.D. on the complete works of senior litterateur Dr. Sunilkumar Lavate.',
      familyTitle: 'Family Background',
      family: 'Born into a humble family — his father worked as a carpenter and construction labourer, his mother rose at four every morning to carry the household. His parents prioritised their children\u2019s education above all, even mortgaging farmland and borrowing so their children could study. The drought-stricken 1980s were hard years.',
      eduTitle: 'Education',
      edu: 'Primary and secondary schooling in his native Shirgaon. D.Ed. from Petala, Kolhapur; college at Bhogawati College, Kurukali. While working, he completed his B.Ed. at Acharya Jawadekar College, Gargoti, and later a Ph.D. from Shivaji University on the complete works of Dr. Sunilkumar Lavate.',
      infoTitle: 'Personal Details',
      info: [
        { k: 'Full name', v: 'Dr. Vishwas Indubai Bandu Sutar' },
        { k: 'Born', v: '2 June 1973 — Shirgaon, Radhanagari, Kolhapur' },
        { k: 'Education', v: 'M.A., B.Ed., Ph.D. (Marathi)' },
        { k: 'Music', v: 'Sangeet Visharad (Classical Vocal) — Akhil Bharatiya Gandharva Mahavidyalaya, Miraj' },
        { k: 'Currently', v: 'Administrative Officer, Education sector' },
      ],
      quote: 'Perseverance was the only way forward.',
      writingTitle: 'Writing & Literature',
      writing: 'Through the series Sanvadi Vichar, Khalilvani and Mulas Patra he has spread positive thought, while encouraging teachers and emerging writers through workshops and initiatives. His writing dwells on social reflection and positive change.',
      awardsTitle: 'Awards & Honours',
      awards: [
        'Rajarshi Chhatrapati Shahu Award — Zilla Parishad, Kolhapur',
        'Swararatna Award — Maiboli Pratishthan, Radhanagari',
        'Granth Award — Sant Gadge Maharaj Adhyasan, Kolhapur',
        'Special Literature Award — Dakshin Maharashtra Sahitya Sabha, Kolhapur',
        'Excellent Biography Award — Balkumar Sahitya Sabha, Kolhapur',
        'Samajratna Award — Shaheed Shivaji Magdum Pratishthan, Pimpalgaon',
        'Outstanding Literature Award — Rajarshi Shahu Library, Thergaon',
        'Literary Award — News Gangadhar, Kolhapur',
        'Late Naib Subhedar Rangrao Desai State-Level Literary Excellence Award — Minche Khurd',
        'Darpan Award — Kolhapur',
        'Kushal Prashasan Adhikari Sanman — Shahuwadi Taluka Shaikshanik Vyaspeeth',
        'Ideal Officer Award — Shivam Educational & Social Organization, Rashiwade Bk.',
      ],
    },
    music: {
      title: 'Music',
      kicker: 'Swara-Sadhana',
      lead: 'An approved singer of All India Radio — known as a vocalist, composer and mentor.',
      ragaTitle: 'Raga Vishwatodi',
      raga: 'Created the new raga "Vishwatodi" — an important milestone in Indian classical music.',
      airTitle: 'All India Radio',
      air: 'Performs as an approved singer of Akashvani (All India Radio).',
      visharadTitle: 'Sangeet Visharad',
      visharad: 'Classical vocal — Akhil Bharatiya Gandharva Mahavidyalaya, Miraj.',
      ytTitle: 'YouTube Channel',
      ytSub: 'Music & thoughts — watch his latest performances',
      ytBtn: 'Visit Channel',
    },
    books: {
      title: 'Books',
      kicker: 'Published Works',
      lead: 'Twelve books spanning the Constitution, saint literature, biography, short stories and literary criticism.',
      featured: 'Latest Release',
      pages: 'Pages',
      price: 'Price',
      publisher: 'Publisher',
      release: 'Released',
      details: 'View Details',
      close: 'Close',
      free: 'Free distribution',
      synopsis: 'About the book',
    },
    samajbhan: {
      title: 'Samajbhan',
      kicker: 'Social Work',
      lead: 'Founder and activist of "Samajbhan", a collective extending a helping hand to the deprived and the needy — 46+ initiatives since 2019.',
      mission: 'Our mission is to help the deprived, poor and needy, and to bring positive change in their lives.',
      timelineTitle: 'Journey of Initiatives',
      readMore: 'Read more',
      readLess: 'Show less',
      galleryTitle: 'Photo Archive',
      gallerySub: 'Field visits and newspaper clippings',
      all: 'All',
    },
    contact: {
      title: 'Contact',
      lead: 'Reach out for lectures, music performances, literary programmes or Samajbhan work.',
      phone: 'Phone',
      location: 'Location',
      locationV: 'Kolhapur, Maharashtra',
      youtube: 'YouTube',
      rights: 'All rights reserved',
    },
  },
};

window.CATS = [
  { id: 'all', mr: 'सर्व', en: 'All' },
  { id: 'med', mr: 'वैद्यकीय', en: 'Medical' },
  { id: 'edu', mr: 'शैक्षणिक', en: 'Education' },
  { id: 'dis', mr: 'दिव्यांग', en: 'Disability' },
  { id: 'eld', mr: 'ज्येष्ठ नागरिक', en: 'Elderly' },
  { id: 'spt', mr: 'क्रीडा व कला', en: 'Sports & Arts' },
  { id: 'soc', mr: 'सामाजिक', en: 'Community' },
];

window.SAMAJBHAN = [
  { id: 1, year: 2019, m: { mr: 'मे २०१९', en: 'May 2019' }, cat: 'dis', img: 'assets/samajbhan/s01.jpeg',
    t: { mr: 'व्हीलचेअर दान', en: 'Wheelchair Donation' },
    d: { mr: 'संगीता पन्हाळकर यांना खामकरवाडी येथे व्हीलचेअर व सीपी कमोड चेअर प्रदान करण्यात आले. मा. राजेंद्र सुर्यवंशी यांच्या हस्ते हा विधायक उपक्रम पार पडला. अनेकांच्या उत्स्फूर्त मदतीतून हा संकल्प साकारला गेला.',
      en: 'Donated a wheelchair and CP commode chair to Sangeeta Panhalakar at Khamkarwadi, led by Hon. Rajendra Suryawanshi — the group\u2019s first act of collective compassion.' } },
  { id: 2, year: 2019, m: { mr: 'जुलै २०१९', en: 'July 2019' }, cat: 'eld', img: null,
    t: { mr: 'मातोश्री वृद्धाश्रम भेट', en: 'Visit to Matoshri Old Age Home' },
    d: { mr: 'मातोश्री वृद्धाश्रम, शिंगणापूर येथे भेट देऊन गहू, ज्वारी, डाळी, तेल अशी आवश्यक जीवनसामग्री प्रदान करण्यात आली. वृद्धांना दिलासा देण्याचा प्रयत्न झाला.',
      en: 'Visited Matoshri Old Age Home, Shinganapur, providing wheat, pulses and oil — sharing warmth with the elderly residents.' } },
  { id: 3, year: 2019, m: { mr: 'जुलै २०१९', en: 'July 2019' }, cat: 'eld', img: null,
    t: { mr: 'आर.के.नगर वृद्धाश्रम मदत', en: 'Help to RK Nagar Old Age Home' },
    d: { mr: 'समाजभानचे तिसरे पाऊल म्हणून आर.के.नगर मातोश्री वृद्धाश्रमास धान्य, तेल, डाळी प्रदान करण्यात आल्या. रूपाली विवेक पाटील यांचे महत्त्वपूर्ण योगदान मिळाले.',
      en: 'Extended support to RK Nagar Matoshri Old Age Home with grains, pulses and cooking oil.' } },
  { id: 4, year: 2019, m: { mr: 'सप्टेंबर २०१९', en: 'September 2019' }, cat: 'dis', img: null,
    t: { mr: 'विशेष नवदांपत्यास मदत', en: 'Support to Special Newlyweds' },
    d: { mr: 'पौर्णिमा आणि सिद्धार्थ या विशेष नवदांपत्यास रोख रक्कम व भेटवस्तू देऊन सन्मानित करण्यात आले. मूकबधीर, निराधार वधू आणि गतिमंद मुलाच्या विवाहाचा धाडसी निर्णय समाजासाठी प्रेरणादायी ठरला.',
      en: 'Honoured a hearing-impaired bride and differently-abled groom with gifts and financial help — a courageous, inspiring marriage.' } },
  { id: 5, year: 2019, m: { mr: 'ऑक्टोबर २०१९', en: 'October 2019' }, cat: 'edu', img: 'assets/samajbhan/s04.jpeg',
    t: { mr: 'व्यक्तिमत्व विकास शिबिर', en: 'Personality Development Camp' },
    d: { mr: 'समाजभान समूह व विठ्ठल मंदिर ट्रस्ट नंदवाळ यांच्या संयुक्त विद्यमाने विद्यार्थ्यांसाठी विनामूल्य व्यक्तिमत्व विकास शिबिर आयोजित करण्यात आले. कला, क्रीडा, संस्कृती, योगा व मानवी मूल्यांवर तज्ज्ञांचे मार्गदर्शन झाले.',
      en: 'A free personality development camp at Vitthal Mandir, Nandwal — experts guided students on arts, sports, yoga and human values.' } },
  { id: 6, year: 2019, m: { mr: 'ऑक्टोबर २०१९', en: 'October 2019' }, cat: 'med', img: null,
    t: { mr: 'सागर पाटील कुटुंबास मदत', en: 'Help to Sagar Patil\u2019s Family' },
    d: { mr: 'कोथळी येथील सागर पाटील यांच्या पत्नीचे कॅन्सरने निधन झाल्यानंतर समूहाने त्यांच्या घरी भेट देऊन आर्थिक मदत व मानसिक आधार दिला.',
      en: 'After Sagar Patil\u2019s wife passed away from cancer, the group visited his home with financial help and emotional support.' } },
  { id: 7, year: 2019, m: { mr: 'नोव्हेंबर २०१९', en: 'November 2019' }, cat: 'med', img: 'assets/samajbhan/s05.jpeg',
    t: { mr: 'संग्राम सुतार (कॅन्सर रुग्ण) मदत', en: 'Help to Cancer Patient Sangram Sutar' },
    d: { mr: 'मुडशिंगी ता. करवीर येथील संग्राम सुतार यांच्या कुटुंबास कॅन्सर उपचारासाठी वैद्यकीय सहाय्य व मानसिक आधार देण्यात आला.',
      en: 'Visited Sangram Sutar of Mudshingi and extended financial aid for his cancer treatment.' } },
  { id: 8, year: 2019, m: { mr: 'डिसेंबर २०१९', en: 'December 2019' }, cat: 'med', img: null,
    t: { mr: 'प्राजक्ता पाटील (किडनी रुग्ण) मदत', en: 'Aid to Kidney Patient Prajakta Patil' },
    d: { mr: 'कणेरी येथील किडनीग्रस्त प्राजक्ता पाटील व तिच्या मोलमजुरी करणाऱ्या आईस भेट देऊन मदतीचा हात दिला. उपचारासाठी सर्वांनी एकत्रित प्रयत्न केले.',
      en: 'Helped young kidney patient Prajakta Patil of Kaneri and her mother, a daily-wage labourer, in their struggle for treatment.' } },
  { id: 9, year: 2019, m: { mr: 'डिसेंबर २०१९', en: 'December 2019' }, cat: 'edu', img: 'assets/samajbhan/s06.jpeg',
    t: { mr: 'बालकल्याण संकुलास शैक्षणिक साहित्य', en: 'Educational Material to Orphanage' },
    d: { mr: 'आदर्श शिक्षक कै. बाजीराव पाटील यांच्या स्मृतिदिनानिमित्त बालकल्याण संकुल, कोल्हापूर येथे शैक्षणिक साहित्य व धान्य प्रदान केले.',
      en: 'Donated educational materials and grains to Balakalyan Sankul orphanage, Kolhapur, in memory of teacher Bajirao Patil.' } },
  { id: 10, year: 2020, m: { mr: 'जानेवारी २०२०', en: 'January 2020' }, cat: 'dis', img: null,
    t: { mr: 'दिव्यांग भावंडांना मदत', en: 'Support to Disabled Brothers' },
    d: { mr: 'मंगळवार पेठ, कोल्हापूर येथील बोन ग्रोथ हार्मोन्सग्रस्त व कर्णबधिर सुरज आणि आदित्य शिंदे या दोन भावंडांना भेट देऊन मदतीचा हात दिला.',
      en: 'Financial and moral support to brothers Suraj and Aditya Shinde, suffering from bone growth disorder and hearing impairment.' } },
  { id: 11, year: 2020, m: { mr: 'मार्च २०२०', en: 'March 2020' }, cat: 'edu', img: 'assets/samajbhan/s07.jpeg',
    t: { mr: 'शाळा विकास मदत', en: 'School Development Help' },
    d: { mr: 'भुदरगड तालुक्यातील माडेकरवाडी शाळेस विकासासाठी निधी प्रदान केला. गुणवत्तावाढीसाठी प्रयत्न करणाऱ्या शिक्षकांचा सन्मानही करण्यात आला.',
      en: 'Development fund for MadeKarwadi ZP School in remote Bhudargad; dedicated teachers were felicitated.' } },
  { id: 12, year: 2020, m: { mr: 'एप्रिल २०२०', en: 'April 2020' }, cat: 'soc', img: 'assets/samajbhan/s08.jpeg',
    t: { mr: 'कोविड लॉकडाऊनमध्ये अन्नधान्य मदत', en: 'Food Aid during COVID Lockdown' },
    d: { mr: 'विजापूर व फुलेवाडी रिंगरोडवरील लमाणी व नंदीबैल कुटुंबांना अन्नधान्याचे वाटप करून सामाजिक बांधिलकी जपली.',
      en: 'Distributed food kits to 55 needy Lamani and bull-owner families in Kolhapur during the COVID crisis.' } },
  { id: 13, year: 2020, m: { mr: 'मे २०२०', en: 'May 2020' }, cat: 'soc', img: null,
    t: { mr: 'व्हाईट आर्मी स्वयंसेवकांना मदत', en: 'Help to White Army Volunteers' },
    d: { mr: 'व्हाईट आर्मी अन्नछत्र कॅम्पला डाळ, तेल, गहू, तांदूळ, कडधान्यांची मदत देण्यात आली. विनामानधन कार्य करणाऱ्या तरुणांचा उत्साह वाखाणण्याजोगा होता.',
      en: 'Donated grains, pulses and oil to the White Army community kitchen feeding the poor during lockdown.' } },
  { id: 14, year: 2020, m: { mr: 'ऑगस्ट २०२०', en: 'August 2020' }, cat: 'edu', img: 'assets/samajbhan/s09.jpeg',
    t: { mr: 'शिक्षक कथालेखन उपक्रम', en: 'Teacher Story-Writing Initiative' },
    d: { mr: 'शिक्षकांच्या संवेदनशील अनुभवांवर आधारित कथालेखन स्पर्धा आयोजित करण्यात आली. निवडक कथांचा \u2018नाळ\u2019 या संग्रहात समावेश करण्यात आला.',
      en: 'A story-writing competition on teachers\u2019 sensitive classroom experiences — selected stories were published as the collection \u2018Nal\u2019.' } },
  { id: 15, year: 2020, m: { mr: 'ऑगस्ट २०२०', en: 'August 2020' }, cat: 'med', img: null,
    t: { mr: 'माऊली केअर सेंटर मदत', en: 'Support to Mauli Care Center' },
    d: { mr: 'स्वातंत्र्यदिनी "माऊली केअर सेंटर"ला मदतीचा हात देऊन समूहाने सामाजिक बांधिलकी जपली.',
      en: 'Extended support to Mauli Care Center on Independence Day.' } },
  { id: 16, year: 2020, m: { mr: 'ऑक्टोबर २०२०', en: 'October 2020' }, cat: 'med', img: null,
    t: { mr: 'किडनी प्रत्यारोपण मदत', en: 'Help for Kidney Transplant' },
    d: { mr: 'वसगडे ता. करवीर येथील राजेंद्र शिंदे यांच्या मुलाच्या किडनी प्रत्यारोपणासाठी मदतीचा हात दिला.',
      en: 'Supported Rajendra Shinde\u2019s family of Vasagade, whose son required an urgent kidney transplant.' } },
  { id: 17, year: 2020, m: { mr: 'डिसेंबर २०२०', en: 'December 2020' }, cat: 'med', img: 'assets/samajbhan/s10.jpeg',
    t: { mr: 'अपघातग्रस्त मारुती जाधव मदत', en: 'Support to Accident Victim Maruti Jadhav' },
    d: { mr: 'पन्हाळा येथील सर्वशिक्षा अभियानातील कर्मचारी मारुती जाधव यांच्या अपघातानंतर उपचारासाठी मदत करण्यात आली.',
      en: 'Helped Maruti Jadhav, an SSA employee from Panhala, after a serious accident requiring costly surgery.' } },
  { id: 18, year: 2021, m: { mr: 'फेब्रुवारी २०२१', en: 'February 2021' }, cat: 'med', img: null,
    t: { mr: 'सिद्धी कांबळे (रक्तकॅन्सर) मदत', en: 'Help to Siddhi Kamble (Blood Cancer)' },
    d: { mr: 'आडूर येथील चौथीतील सिद्धी मोहन कांबळे या लेकरास रक्तकॅन्सरचे निदान झाल्याने स्टार हॉस्पिटल येथे भेट देऊन मदत केली.',
      en: 'Financial assistance to 4th-grader Siddhi Kamble of Adoor, diagnosed with blood cancer.' } },
  { id: 19, year: 2021, m: { mr: 'मार्च २०२१', en: 'March 2021' }, cat: 'spt', img: 'assets/samajbhan/s11.jpeg',
    t: { mr: 'युवा पैलवान सारंग ढेंगे मदत', en: 'Help to Young Wrestler Sarang Dhenge' },
    d: { mr: 'पाडळी खुर्द येथील होतकरू पैलवान सारंग संभाजी ढेंगे याच्या कुटुंबास मदतीचा हात दिला.',
      en: 'Assisted young wrestler Sarang Dhenge of Padali Khurd, whose family struggled to support his wrestling career.' } },
  { id: 20, year: 2021, m: { mr: 'जुलै २०२१', en: 'July 2021' }, cat: 'soc', img: null,
    t: { mr: 'पूजा गाडेकर मदत', en: 'Support to Pooja Gadekar' },
    d: { mr: 'पूजा गाडेकर हिच्या संघर्षमय प्रवासास समूहातर्फे मदतीचा हात देण्यात आला.',
      en: 'Extended help to Pooja Gadekar during her challenging personal journey.' } },
  { id: 21, year: 2021, m: { mr: 'सप्टेंबर २०२१', en: 'September 2021' }, cat: 'spt', img: 'assets/samajbhan/s12.jpeg',
    t: { mr: 'ज्येष्ठ तबलावादकास मदत', en: 'Help to Senior Tabla Player' },
    d: { mr: 'कोरोनामुळे उपजीविकेवर संकट आलेल्या ज्येष्ठ तबलावादकाच्या कुटुंबास धान्य व रोख मदत दिली.',
      en: 'Food supplies and cash aid to an elderly tabla player who lost his livelihood during COVID.' } },
  { id: 22, year: 2021, m: { mr: 'ऑक्टोबर २०२१', en: 'October 2021' }, cat: 'spt', img: null,
    t: { mr: 'राष्ट्रीय सायकलपटू विरेंद्र पाटील मदत', en: 'Aid to National Cyclist Virendra Patil' },
    d: { mr: 'कुडित्रे येथील गरजू राष्ट्रीय सायकलपटू विरेंद्र पाटील याला आर्थिक मदत देण्यात आली.',
      en: 'Financial support to national cyclist Virendra Patil of Kuditre to continue his sports career.' } },
  { id: 23, year: 2021, m: { mr: 'नोव्हेंबर २०२१', en: 'November 2021' }, cat: 'med', img: 'assets/samajbhan/s13.jpeg',
    t: { mr: 'दिपाली द्राक्षे (एस.टी. वाहक) मदत', en: 'Help to Dipali Drakshe (ST Conductor)' },
    d: { mr: 'ब्रेन हेमरेज झालेल्या एस.टी. वाहक दिपाली द्राक्षे यांना प्रत्यक्ष भेट देऊन आर्थिक मदत व मानसिक आधार दिला.',
      en: 'Financial and emotional support to ST conductor Dipali Drakshe, suffering from brain haemorrhage.' } },
  { id: 24, year: 2022, m: { mr: 'जानेवारी २०२२', en: 'January 2022' }, cat: 'med', img: null,
    t: { mr: 'लकवाग्रस्त शिवाजी पाटील मदत', en: 'Help to Paralysed Shivaji Patil' },
    d: { mr: 'कौलव येथील लकवा व ब्रेन ट्यूमरग्रस्त शिवाजी राऊ पाटील यांच्या कुटुंबास मदतीचा हात दिला.',
      en: 'Assisted the family of paralysed brain-tumour patient Shivaji Patil of Kaulav.' } },
  { id: 25, year: 2022, m: { mr: 'फेब्रुवारी २०२२', en: 'February 2022' }, cat: 'dis', img: 'assets/samajbhan/s14.jpeg',
    t: { mr: 'दिव्यांग शूटर जानकी मोकाशी मदत', en: 'Support to Para-Shooter Janaki Mokashi' },
    d: { mr: 'सदर बाजार, कोल्हापूर येथील दिव्यांग शूटर जानकी मोकाशी यांना पॅरा ऑलिंपिक शूटिंगसाठी आर्थिक मदत देण्यात आली.',
      en: 'Funds for para-shooter Janaki Mokashi of Kolhapur towards training equipment and national shooting events.' } },
  { id: 26, year: 2022, m: { mr: 'एप्रिल २०२२', en: 'April 2022' }, cat: 'soc', img: 'assets/samajbhan/s15.jpeg',
    t: { mr: '\u2018उमेद\u2019 अनाथ उपक्रम मदत', en: 'Support to \u2018Umed\u2019 Orphan Initiative' },
    d: { mr: '\u2018उमेद\u2019 ही वंचित मुलांसाठी काम करणारी छोटी संस्था — प्रकाश गाताडे आणि सहकाऱ्यांच्या \u2018मायेची सावली\u2019 उभारण्याच्या कार्यास हातभार लावला.',
      en: 'In its 25th milestone activity, supported \u2018Umed\u2019, an organisation for underprivileged and orphan children.' } },
  { id: 27, year: 2022, m: { mr: 'जून २०२२', en: 'June 2022' }, cat: 'med', img: null,
    t: { mr: 'इकबाल जमादार, गडहिंग्लज मदत', en: 'Help to Iqbal Jamadar, Gadhinglaj' },
    d: { mr: 'सर्व शिक्षा अभियानातील विषयतज्ज्ञ इकबाल जमादार यांना \u2018मोयामोया\u2019 हा मेंदूचा दुर्मिळ आजार झाला. मुंबईतील तात्काळ ऑपरेशनसाठी सुमारे ८ लाख खर्च अपेक्षित होता. समूहाने संवेदनशीलतेने आर्थिक हातभार दिला.',
      en: 'Iqbal Jamadar, an SSA subject expert, was diagnosed with rare Moyamoya disease requiring urgent surgery in Mumbai. The group contributed towards the ₹8-lakh expense.' } },
  { id: 28, year: 2022, m: { mr: 'सप्टेंबर २०२२', en: 'September 2022' }, cat: 'soc', img: 'assets/samajbhan/s16.jpeg',
    t: { mr: 'पांजरपोळ संस्था, शाहूपुरी भेट', en: 'Visit to Panjarpol Sanstha, Shahupuri' },
    d: { mr: 'प्राण्यांप्रतीही संवेदना जपण्यासाठी १९०६ मध्ये छत्रपती शाहू महाराजांच्या मदतीने सुरू झालेल्या पांजरपोळ संस्थेस भेट देऊन मदतीचा हात दिला. ही संस्था मोकाट, आजारी गाई-बैल, घोडे अशा प्राण्यांना सांभाळते.',
      en: 'Extended help to Panjarpol Sanstha (est. 1906 with the help of Chhatrapati Shahu Maharaj), which shelters stray, blind and ailing cattle and horses.' } },
  { id: 29, year: 2022, m: { mr: 'नोव्हेंबर २०२२', en: 'November 2022' }, cat: 'dis', img: 'assets/samajbhan/s17.jpeg',
    t: { mr: 'अंधशाळा, कोल्हापूर — ग्रंथालय कपाट', en: 'Library Cupboard to Blind School' },
    d: { mr: 'ज्ञानप्रबोधन भवन संचलित अंधशाळा, मंगळवार पेठ येथे भेट देऊन मुलांचे संगीत सादरीकरण पाहिले. शाळेस ग्रंथालय कपाट प्रदान करण्यात आले. शिक्षणाधिकारी मा. आशा उबाळे उपस्थित होत्या.',
      en: 'Visited the blind school at Mangalwar Peth, enjoyed the children\u2019s music performance, and donated a library cupboard to the school.' } },
  { id: 30, year: 2023, m: { mr: 'जानेवारी २०२३', en: 'January 2023' }, cat: 'soc', img: null,
    t: { mr: 'शीतल भाकरे, फुलेवाडी मदत', en: 'Support to Shital Bhakare, Phulewadi' },
    d: { mr: 'पती हृदयविकार व किडनीच्या आजाराने दवाखान्यात; पदरी दोन मुले — तरीही डोसा सेंटर चालवून संसाराचा गाडा ओढणाऱ्या शीतल भाकरे यांना मानसिक आधार व आर्थिक सहयोग दिला.',
      en: 'Shital Bhakare runs a dosa stall while her husband battles heart and kidney disease. The group offered financial help and moral support.' } },
  { id: 31, year: 2023, m: { mr: 'एप्रिल २०२३', en: 'April 2023' }, cat: 'med', img: 'assets/samajbhan/s18.jpeg',
    t: { mr: 'योगेश सुतार (किडनी रुग्ण) मदत', en: 'Help to Kidney Patient Yogesh Sutar' },
    d: { mr: 'टिंबर मार्केट येथील योगेश सुतार यांच्या दोन्ही किडन्या निकामी झाल्या. वयस्कर आई-वडील, पत्नी, दोन मुले असे कुटुंब संकटात. गुडफ्रायडेच्या दिवशी घरी भेट देऊन आर्थिक हातभार लावला.',
      en: 'Both kidneys of 30-year-old Yogesh Sutar failed. The group visited his home on Good Friday with financial support for his family.' } },
  { id: 32, year: 2023, m: { mr: 'एप्रिल २०२३', en: 'April 2023' }, cat: 'edu', img: 'assets/samajbhan/s19.jpeg',
    t: { mr: 'चिल्लर पार्टी चित्रपट महोत्सव', en: 'Chillar Party Film Festival' },
    d: { mr: 'दाजीपूर (राधानगरी) येथील दुर्गम भागातील ३०० मुलांना शाहू स्मारक भवन येथे उत्कृष्ट चित्रपट दाखवणे, टाऊन हॉल, राजवाडा दाखवणे या अभिनव उपक्रमास आर्थिक सहयोग दिला.',
      en: 'Sponsored a film festival bringing 300 children from remote Dajipur to Kolhapur to watch world cinema and visit the Town Hall and Rajwada.' } },
  { id: 33, year: 2023, m: { mr: 'जून २०२३', en: 'June 2023' }, cat: 'med', img: null,
    t: { mr: 'शहाजी जाधव, कोथळी मदत', en: 'Help to Shahaji Jadhav, Kothali' },
    d: { mr: 'दोन्ही किडन्या निकामी झालेल्या शहाजी ज्ञानदेव जाधव यांना आठवड्यातून दोन डायलिसिस करावे लागत होते. घरी भेट देऊन कुटुंबास आर्थिक मदत केली.',
      en: 'Shahaji Jadhav needed dialysis twice a week after both kidneys failed. The group visited his home and helped the family financially.' } },
  { id: 34, year: 2023, m: { mr: 'जुलै २०२३', en: 'July 2023' }, cat: 'edu', img: 'assets/samajbhan/s20.jpeg',
    t: { mr: 'स्वरूप धनवडे — IIT खरगपूर प्रोत्साहन', en: 'Encouraging Swarup Dhanwade — IIT Kharagpur' },
    d: { mr: 'टेलरिंग व्यवसाय करणाऱ्या धनवडे दांपत्याचा मुलगा स्वरूप IIT खरगपूरसाठी निवडला गेला. त्याच्या घरी भेट देऊन कौतुक, शिक्षणासाठी आर्थिक हातभार आणि सारथी शिष्यवृत्तीसाठी मार्गदर्शन केले.',
      en: 'Swarup, son of a tailor couple, was selected for IIT Kharagpur. The group visited, contributed towards his education and guided him for the Sarathi scholarship.' } },
  { id: 35, year: 2023, m: { mr: 'सप्टेंबर २०२३', en: 'September 2023' }, cat: 'med', img: null,
    t: { mr: 'श्रुतिका दळवी उपचार मदत', en: 'Treatment Help for Shrutika Dalavi' },
    d: { mr: 'शिष्यवृत्ती व NMMS परीक्षेत यश मिळवणारी श्रुतिका अपघातात गंभीर जखमी झाली; पाच वर्षांचा भाऊ जागीच ठार झाला. हॉस्पिटलमध्ये भेट देऊन तिच्या आईकडे रोख रक्कम सुपूर्द केली.',
      en: 'Scholarship-winner Shrutika was critically injured in an accident that killed her five-year-old brother. The group visited the hospital and handed financial aid to her mother.' } },
  { id: 36, year: 2023, m: { mr: 'ऑक्टोबर २०२३', en: 'October 2023' }, cat: 'med', img: null,
    t: { mr: 'अथर्व (रक्तकॅन्सर) उपचार मदत', en: 'Help for Atharva\u2019s Cancer Treatment' },
    d: { mr: 'इचलकरंजी येथील कल्पना केस्ती यांचा मुलगा अथर्व (दहावीत ९०.४०%) याला ब्लड कॅन्सर झाला. पती पंधरा वर्षे बेपत्ता; खाजगी अकॅडमीत काम करत कल्पना गुजराण करतात. समूहाने आर्थिक मदत केली.',
      en: 'Atharva, a bright student (90.40% in SSC), was diagnosed with blood cancer. His mother Kalpana raises him alone — the group extended financial help.' } },
  { id: 37, year: 2024, m: { mr: 'फेब्रुवारी २०२४', en: 'February 2024' }, cat: 'soc', img: null,
    t: { mr: 'पंचगंगा स्मशानभूमीस १५,००० शेणी', en: '15,000 Dung-Cakes to Panchganga Crematorium' },
    d: { mr: 'महानगरपालिका अंत्यसंस्कार मोफत करते; पण शेणींचा तुटवडा असल्याचे वृत्त प्रसिद्ध होताच समूहाने पंचगंगा स्मशानभूमीस १५,००० शेणी प्रदान केल्या.',
      en: 'On reading of a shortage at the free municipal crematorium, the group immediately donated 15,000 dung-cakes to Panchganga crematorium.' } },
  { id: 38, year: 2024, m: { mr: 'मार्च २०२४', en: 'March 2024' }, cat: 'soc', img: null,
    t: { mr: 'नारायण खोत कुटुंबास आधार', en: 'Support to Narayan Khot\u2019s Family' },
    d: { mr: 'निकमवाडी ता. पन्हाळा येथील नारायण खोत यांचा अपघाती मृत्यू झाला. त्यांच्या पश्चात पत्नी व दोन मुले परावलंबी झाली. कुटुंबास भेट देऊन सांत्वन, मानसिक आधार व आर्थिक हातभार दिला.',
      en: 'After Narayan Khot\u2019s accidental death left his wife and two children dependent, the group visited to console and support the family.' } },
  { id: 39, year: 2024, m: { mr: 'मे २०२४', en: 'May 2024' }, cat: 'soc', img: null,
    t: { mr: 'रमेश पाटील — धडपडणारा बाप', en: 'Ramesh Patil — A Struggling Father' },
    d: { mr: 'कसबा बावडा येथील रमेश पाटील यांना पाच मुले; पत्नीचे निधन आठ वर्षांपूर्वी झाले. तीन मुले मूकबधीर. या धडपडणाऱ्या बापाला आर्थिक मदत आणि समाज सोबत असल्याचे मानसिक बळ दिले.',
      en: 'Widowed father of five — three hearing-impaired — Ramesh Patil received financial help and the reassurance that society stands with him.' } },
  { id: 40, year: 2024, m: { mr: 'जून २०२४', en: 'June 2024' }, cat: 'dis', img: null,
    t: { mr: 'आनंदा सुतार — घरकुल मदत', en: 'Housing Help to Ananda Sutar' },
    d: { mr: 'आमजाई व्हरवडे येथील आनंदा सुतार हे स्वतः दिव्यांग व आजारी; बहीणही दिव्यांग. त्यांच्या घरकुल बांधकामातील अडचणींत समूहाने आर्थिक मदत केली.',
      en: 'Ananda Sutar, disabled and ailing, struggled to complete his house. The group contributed financially towards its construction.' } },
  { id: 41, year: 2024, m: { mr: 'ऑगस्ट २०२४', en: 'August 2024' }, cat: 'soc', img: null,
    t: { mr: 'वारांगणा भगिनींना मदत', en: 'Help to Sex Workers\u2019 Families' },
    d: { mr: 'अतिवृष्टी काळात कनाननगर येथील वारांगणा सखी संघटनेतील भगिनी व कुटुंबीयांची उपासमार झाली; औषधोपचारास पैसे नव्हते. या उपेक्षित घटकास आर्थिक मदत करून त्यांचे जीवन समजून घेतले.',
      en: 'During heavy floods, the group extended financial help to sex workers and their families at Kanannagar who faced hunger and lacked money for medicines.' } },
  { id: 42, year: 2024, m: { mr: 'डिसेंबर २०२४', en: 'December 2024' }, cat: 'dis', img: 'assets/samajbhan/s02.jpeg',
    t: { mr: 'स्वयम विशेष मुलांची शाळा मदत', en: 'Support to Swayam Special School' },
    d: { mr: 'स्वयम विशेष मुलांची शाळा, कसबा बावडा येथे दिव्यांग आणि विशेष मुलांना समजून घेत मदतीचा हात दिला. मुख्याध्यापक प्रमोद भिसे व सहकाऱ्यांचे विशेष कौतुक वाटले.',
      en: 'Extended a helping hand to Swayam School for special children at Kasaba Bawada, appreciating headmaster Pramod Bhise and his colleagues.' } },
  { id: 43, year: 2025, m: { mr: 'फेब्रुवारी २०२५', en: 'February 2025' }, cat: 'med', img: null,
    t: { mr: 'वैष्णवी कांबळे उपचार मदत', en: 'Treatment Help for Vaishnavi Kamble' },
    d: { mr: 'NMMS राज्य गुणवत्ता यादीतील वैष्णवीला मेंदूचा विकार आढळला. वडील ऊसतोड कामगार, आई शेतमजूर. रोजच्या इंजेक्शनचा खर्चही न परवडणारा. घरी भेट देऊन आर्थिक हातभार व कुटुंबाला मानसिक आधार दिला.',
      en: 'Vaishnavi, an NMMS state merit-list student, was diagnosed with a brain disorder her farm-labourer parents could not afford to treat. The group visited with financial help.' } },
  { id: 44, year: 2025, m: { mr: 'जून २०२५', en: 'June 2025' }, cat: 'eld', img: null,
    t: { mr: 'लक्ष्मण कारंडे — वयोवृद्धांना आधार', en: 'Support to Elderly Laxman Karande' },
    d: { mr: 'गणेशवाडी येथील वयोवृद्ध लक्ष्मण कारंडे पत्नी व नातवासह पडक्या घरात राहतात. त्यांचे अपूर्ण बांधकाम पूर्ण होण्यासाठी उभयतांना आर्थिक मदत देऊ केली.',
      en: 'Elderly Laxman Karande lives with his wife and grandson in a crumbling house. The group offered financial help to complete its construction.' } },
  { id: 45, year: 2026, m: { mr: 'फेब्रुवारी २०२६', en: 'February 2026' }, cat: 'med', img: 'assets/samajbhan/s04.jpeg',
    t: { mr: 'विनायक माईंगडे उपचार मदत', en: 'Treatment Help for Vinayak Maingde' },
    d: { mr: 'कोतोली येथील नववीतील विनायकचा गंभीर अपघात झाला; वडीलही जखमी. हॉस्पिटल खर्च १५ लाखांहून अधिक. मेंदूच्या ऑपरेशननंतर हॉस्पिटलमध्ये भेट देऊन कुटुंबाकडे आर्थिक मदत सुपूर्द केली.',
      en: 'Ninth-grader Vinayak suffered a grave accident with hospital costs above ₹15 lakh. The group visited after his brain surgery and handed financial aid to the family.' } },
  { id: 46, year: 2026, m: { mr: 'मे २०२६', en: 'May 2026' }, cat: 'med', img: 'assets/samajbhan/s03.jpeg',
    t: { mr: 'महेंद्र कुडाळकर — रुग्णवाहिका चालक मदत', en: 'Help to Ambulance Driver Mahendra Kudalkar' },
    d: { mr: 'सडोली खालसा येथील महेंद्र कुडाळकर बारा वर्षे १०८ रुग्णवाहिकेचे चालक होते. \u2018मोटो न्यूरॉन\u2019 या असाध्य आजाराने ते ग्रस्त झाले. घरी भेट देऊन विचारपूस, मानसिक आधार आणि आर्थिक मदत केली.',
      en: 'Mahendra Kudalkar drove the 108 ambulance for twelve years before motor neurone disease left him paralysed. The group visited his home with moral support and financial help.' } },
];

window.GALLERY = [
  'assets/samajbhan/s01.jpeg','assets/samajbhan/s06.jpeg','assets/samajbhan/s11.jpeg','assets/samajbhan/s16.jpeg',
  'assets/samajbhan/s02.jpeg','assets/samajbhan/s07.jpeg','assets/samajbhan/s12.jpeg','assets/samajbhan/s17.jpeg',
  'assets/samajbhan/s03.jpeg','assets/samajbhan/s08.jpeg','assets/samajbhan/s13.jpeg','assets/samajbhan/s18.jpeg',
  'assets/samajbhan/s05.jpeg','assets/samajbhan/s09.jpeg','assets/samajbhan/s14.jpeg','assets/samajbhan/s19.jpeg',
  'assets/samajbhan/s04.jpeg','assets/samajbhan/s10.jpeg','assets/samajbhan/s15.jpeg','assets/samajbhan/s20.jpeg',
];

window.BOOKS = [
  { id: 10, cover: 'assets/books/amritmanthan.jpeg', price: '₹200', pages: 191, featured: true,
    title: { mr: 'अमृत मंथन', en: 'Amrit Manthan' },
    sub: { mr: 'भाषण संग्रह', en: 'Speech Collection' },
    publisher: { mr: 'अक्षर दालन, कोल्हापूर', en: 'Akshar Dalan, Kolhapur' },
    release: { mr: '११ एप्रिल २०२४', en: '11 April 2024' },
    brief: { mr: 'डॉ. सुनीलकुमार लवटे यांच्या अमृत महोत्सवी वर्षानिमित्त झालेल्या व्याख्याने, शिक्षण परिषद, इतिहास परिषद अशा उपक्रमांतील निवडक तेरा भाषणांचे संपादित संकलन.',
      en: 'Thirteen selected and edited speeches from the events celebrating Dr. Sunilkumar Lavate\u2019s 75th (Amrit Mahotsav) year — lectures, education conferences and a history convention.' },
    synopsis: { mr: 'डॉ. सदानंद मोरे, डॉ. दामोदर खडसे, प्रबोधनकार इंद्रजित देशमुख, डॉ. विवेक सावंत, प्रा. सुरेश द्वादशीवार, डॉ. बी. एम. हिर्डेकर अशा महनीय वक्त्यांच्या भाषणांचा समावेश या ग्रंथात आहे. डॉ. लवटे यांनी नागरी सत्कार प्रसंगी व्यक्त केलेले भावशील मनोगतही समाविष्ट आहे. विविध विषयांवरील विचारमंथनामुळे ग्रंथास \u2018अमृत मंथन\u2019 हे सूचक शीर्षक देण्यात आले आहे.',
      en: 'The volume includes speeches by eminent personalities such as Dr. Sadanand More, Dr. Damodar Khadse, Indrajit Deshmukh, Dr. Vivek Sawant, Prof. Suresh Dwadashiwar and Dr. B. M. Hirdekar, along with Dr. Lavate\u2019s moving address at his civic felicitation. As this churning of ideas took place in his Amrit Mahotsav year, the book is aptly titled \u2018Amrit Manthan\u2019.' } },
  { id: 12, cover: 'assets/books/lavate_vimarsh.jpeg', price: '₹550', pages: 376,
    title: { mr: 'सुनीलकुमार लवटे : साहित्य विमर्श', en: 'Sunilkumar Lavate: Literary Discourse' },
    sub: { mr: 'समीक्षा ग्रंथ', en: 'Literary criticism' },
    publisher: { mr: 'संस्कृती प्रकाशन, पुणे', en: 'Sanskriti Publications, Pune' },
    release: { mr: '२०२५', en: '2025' },
    brief: { mr: 'डॉ. सुनीलकुमार लवटे यांच्या समग्र मराठी साहित्याचा विस्तृत व तपशीलवार अभ्यास मांडणारा समीक्षा ग्रंथ.',
      en: 'A wide and detailed critical study of Dr. Sunilkumar Lavate\u2019s complete Marathi literary works.' },
    synopsis: { mr: '\u2018सुनीलकुमार लवटे : साहित्य विमर्श\u2019 हा ग्रंथ डॉ. लवटे यांच्या साहित्याच्या अभ्यासकांसाठी एक महत्त्वाचा संदर्भग्रंथ ठरेल, असा मला विश्वास वाटतो. — डॉ. तारा भवाळकर (प्रस्तावनेतून)',
      en: '\u201cThe book will undoubtedly serve as a significant reference for researchers studying Dr. Lavate\u2019s literature.\u201d — Dr. Tara Bhavalakar (from the Preface)' } },
  { id: 9, cover: 'assets/books/mulas-patra.jpeg', price: '₹150', pages: 100,
    title: { mr: 'मुलास पत्र', en: 'Mulas Patra (Letters to My Child)' },
    sub: { mr: 'संवादी साहित्य', en: 'Epistolary literature' },
    publisher: { mr: 'अक्षर दालन, कोल्हापूर', en: 'Akshar Dalan, Kolhapur' },
    release: { mr: '२०२३', en: '2023' },
    brief: { mr: 'मुलांस पत्रे लिहून पालकांनी समुपदेशन केल्यास पालक-पाल्यात सामंजस्य निर्माण होऊन कौटुंबिक सौहार्द वाढते — हा विश्वास देणारी पत्रमालिका.',
      en: 'A series of letters showing how parents who counsel through writing can build mutual understanding and family harmony with their children.' },
    synopsis: { mr: 'समाजमाध्यमांच्या आहारी जाणाऱ्या काळात पालक-पाल्य संवाद कमी होतो आहे; नात्यातील ओलावा आटतो आहे. अशा काळात कुमारवयात सुरू झालेला संवाद पाल्यास जबाबदार व सुजाण नागरिक बनवेल. हे पुस्तक घरोघरी नेऊन पालकांनी मुलांना वाचावयास दिले तर ते जागृत पालकांचे शहाणपण ठरेल. — डॉ. सुनीलकुमार लवटे',
      en: '\u201cIn an age of social media, dialogue between parents and children is drying up. A conversation begun in childhood will make the child a responsible, wise citizen. If parents take this book home for their children, it will be the wisdom of awakened parents.\u201d — Dr. Sunilkumar Lavate' } },
  { id: 1, cover: 'assets/books/sanvidhan.jpeg', price: '₹300', pages: 210,
    title: { mr: 'भारतीय संविधान आणि लोक', en: 'Indian Constitution and People' },
    sub: { mr: 'वैचारिक ग्रंथ', en: 'Civic thought' },
    publisher: { mr: 'अक्षर दालन, कोल्हापूर', en: 'Akshar Dalan, Kolhapur' },
    release: { mr: '१५ सप्टेंबर २०१९', en: '15 September 2019' },
    brief: { mr: 'संविधानाचा सुलभ भाषेत प्रसार करणारा, लोकांचे हक्क आणि उत्तरदायित्व नेमकेपणाने सांगणारा ग्रंथ. विद्यार्थी, तरुण नागरिक, अभ्यासक, कार्यकर्ते यांच्यासाठी संग्राह्य.',
      en: 'A book that carries the Constitution to people in simple language, precisely stating citizens\u2019 rights and responsibilities — invaluable for students, young citizens, researchers and activists.' },
    synopsis: { mr: 'भारतीय संविधानाच्या पानापानावर आणि प्रत्येक कलमात एक चेहरा दिसतो — तो असतो भारतीय नागरिकाचा! भारतीय संविधान ही केवळ दर्शन घेण्याची गोष्ट नाही, तर \u2018डोक्यात\u2019 घेऊन कृती करण्याची गोष्ट आहे. हा ग्रंथ वाचाल तर ही दृष्टी आपल्यात नक्कीच येईल.',
      en: 'On every page and in every article of the Constitution one sees a face — that of the Indian citizen. The Constitution is not merely to be revered; it is to be taken \u2018into the head\u2019 and acted upon. Read this book and that vision will surely come to you.' } },
  { id: 2, cover: 'assets/books/tukaram.jpeg', price: '₹150', pages: 100,
    title: { mr: 'तुकाराम नावाचा संत माणूस', en: 'Tukaram: The Saint Man' },
    sub: { mr: 'संतसाहित्य', en: 'Saint literature' },
    publisher: { mr: 'अक्षर दालन, कोल्हापूर', en: 'Akshar Dalan, Kolhapur' },
    release: { mr: '१५ नोव्हेंबर २०१९', en: '15 November 2019' },
    brief: { mr: 'क्रांतिकारी, प्रबोधनकार संत तुकारामांना \u2018माणूस\u2019 म्हणून समजून घेणारा, त्यांच्या अभंग गाथेवर नवा प्रकाशझोत टाकणारा ग्रंथ.',
      en: 'Understanding the revolutionary saint Tukaram as a human being — interpreting the key events of his life and shedding new light on his Abhanga poetry.' },
    synopsis: { mr: 'अवघे बेचाळीस वर्षांचे आयुष्य लाभलेल्या तुकारामांचा जीवनप्रवास विस्मयकारी आहे. ध्येय निश्चित होताच त्यांनी संघर्षमय जीवन स्वीकारले आणि आंतरिक-बाह्य संघर्ष अखेरपर्यंत चालू ठेवला. अन्यायी, पाखंडी यांच्यावर शब्दांचे आसूड ओढणाऱ्या तुकारामांना विवेकाने समजून घेऊया — यासाठीच ही साहित्यनिर्मिती!',
      en: 'The life journey of Tukaram, who lived only forty-two years, is astonishing. Once his goal was set, he embraced a life of struggle and carried his inner and outer battles to the very end. Let us understand, with reason, the saint who lashed injustice and hypocrisy with words — that is why this book exists.' } },
  { id: 3, cover: 'assets/books/basvanna.jpeg', price: '₹100', pages: 96,
    title: { mr: 'महात्मा बसवण्णा : जीवन आणि संघर्ष', en: 'Mahatma Basavanna: Life and Struggle' },
    sub: { mr: 'चरित्र', en: 'Biography' },
    publisher: { mr: 'संवाद प्रकाशन, कोल्हापूर', en: 'Sanvad Prakashan, Kolhapur' },
    release: { mr: '१५ ऑगस्ट २०२०', en: '15 August 2020' },
    brief: { mr: 'बाराव्या शतकातील क्रांतिकारी महापुरुषाचे भक्तिप्रधान नव्हे, तर विचारप्रधान चरित्र — माणुसकीच्या वाटेवरचा उजेड.',
      en: 'A thought-oriented (not devotion-oriented) biography of the revolutionary 12th-century reformer — a ray of light for humanity.' },
    synopsis: { mr: 'माणसाचे अध्यात्माचे जग स्वर्ग-नरकाशी न जोडता ते माणसाच्या घामाशी जोडणारा महामानव म्हणजे महात्मा बसवण्णा! श्रद्धांचा महापूर बाजूला ठेवून लिहिलेले हे चरित्र त्यांचे क्रांतिकारी जीवन, विचार आणि कार्य समजावून देते.',
      en: 'Basavanna connected the spiritual world not with heaven and hell but with human sweat. Written by setting aside the flood of blind faith, this biography explains his revolutionary life, thought and work.' } },
  { id: 4, cover: 'assets/books/nal.jpeg', price: '₹250', pages: 168,
    title: { mr: 'नाळ', en: 'Nal' },
    sub: { mr: 'शिक्षकांच्या संवेदनशील अनुभवांच्या कथा', en: 'Stories of teachers\u2019 sensitive experiences' },
    publisher: { mr: 'निर्मिती प्रकाशन, कोल्हापूर', en: 'Nirmiti Prakashan, Kolhapur' },
    release: { mr: '१५ ऑगस्ट २०२१', en: '15 August 2021' },
    brief: { mr: 'शिक्षक आणि विद्यार्थ्याच्या अतूट नात्याच्या संवेदनशील कथा — पंचवीस कथांचे साहित्य संचित.',
      en: 'Twenty-five sensitive stories of the unbreakable bond between teacher and student — a literary treasure.' },
    synopsis: { mr: 'या संग्रहातील पंचवीस कथा वाचताना शिक्षक ही संकल्पना एकूणच समाजपुरुषाचे नाभीस्थान आहे, याचा प्रत्यय येतो. शिक्षक, विद्यार्थी आणि समाज यांच्या नातेसंबंधातील ताणेबाणे उलगडणारा हा विशाल आलेख मराठी वाङ्मयात मोलाची भर घालणारा ठरेल.',
      en: 'Reading these twenty-five stories, one realises the teacher is the very navel of society. Unfolding the weave of relationships between teacher, student and society, \u2018Nal\u2019 is a valuable addition to Marathi literature.' } },
  { id: 11, cover: 'assets/books/khalilvani.jpeg', price: '₹125', pages: 112,
    title: { mr: 'खलिलवाणी', en: 'Khalilvani' },
    sub: { mr: 'महाकवी खलिल जिब्रानच्या विचारांवर मुक्त भाष्य', en: 'A commentary on the thoughts of Kahlil Gibran' },
    publisher: { mr: 'ज्ञानसंवर्धन प्रकाशन, कोल्हापूर', en: 'Dnyansanvardhan Publications, Kolhapur' },
    release: { mr: '—', en: '—' },
    brief: { mr: 'मानवी मूल्यांना जीवनात अढळ स्थान देणाऱ्या महाकवी खलिल जिब्रानच्या विचारांवरील मुक्त भाष्य.',
      en: 'A free commentary on Kahlil Gibran, the poet-philosopher who gave human values an unshakeable place in life.' },
    synopsis: { mr: 'खलिल जिब्रान हा विचारवंत मानवी मूल्यांवर चिंतन करून विश्व-जीवनाशी स्वतःला जोडून घेतो. माणसाच्या हृदयात उचंबळणाऱ्या आशा-आकांक्षा या परमेश्वराच्या, निसर्गाच्या प्रेरणा आहेत, ही खलिलची जीवनविषयक प्रमुख कल्पना. त्याला समजून घेण्यासाठी हा लेखनप्रपंच!',
      en: 'Gibran reflects deeply on human values and connects himself with the universal essence of life — his central idea being that the aspirations rising in the human heart are divine, inspired by nature. This book is an attempt to understand him.' } },
  { id: 7, cover: 'assets/books/bahuvidh.jpeg', price: '₹400', pages: 316,
    title: { mr: 'डॉ. सुनीलकुमार लवटे : बहुविध संवाद', en: 'Dr. Sunilkumar Lavate: Multifaceted Dialogue' },
    sub: { mr: 'मुलाखत संग्रह', en: 'Interview collection' },
    publisher: { mr: 'भाग्यश्री प्रकाशन, कोल्हापूर', en: 'Bhagyashri Prakashan, Kolhapur' },
    release: { mr: '९ ऑक्टोबर २०२२', en: '9 October 2022' },
    brief: { mr: 'डॉ. लवटे यांच्याशी दहा आणि त्यांच्याविषयी बारा — एकूण बावीस मुलाखतींच्या क्ष-किरणातून त्यांच्या जीवन-विचारांची उकल.',
      en: 'Ten interviews with Dr. Lavate and twelve about him — twenty-two conversations that X-ray his life and thought.' },
    synopsis: { mr: 'मुलाखत हा साहित्यातील महत्त्वपूर्ण वाङ्मयप्रकार. डॉ. लवटे यांच्या बहिरंग व अंतरंगाचा शोध घेत दोन भागांत वर्गीकृत बावीस मुलाखतींमधून त्यांचे जीवन, कार्य, विचार आणि वाङ्मय उलगडण्याचा हा प्रयत्न.',
      en: 'The interview is a significant literary genre. Classified in two parts, these twenty-two conversations search Dr. Lavate\u2019s outer and inner worlds, unravelling his life, work, thought and writing.' } },
  { id: 8, cover: 'assets/books/lavateSir.jpeg', price: null, pages: 100,
    title: { mr: 'डॉ. सुनीलकुमार लवटे : जीवन व कार्य', en: 'Dr. Sunilkumar Lavate: Life and Work' },
    sub: { mr: 'चरित्र', en: 'Biography' },
    publisher: { mr: 'नागरी सत्कार समिती, कोल्हापूर', en: 'Civic Felicitation Committee, Kolhapur' },
    release: { mr: '१५ सप्टेंबर २०२२', en: '15 September 2022' },
    brief: { mr: 'ज्येष्ठ साहित्यिक, समीक्षक, संपादक आणि कृतिशील विचारवंत डॉ. सुनीलकुमार लवटे यांच्या जीवनकार्याचा परिचय.',
      en: 'An introduction to the life and work of senior litterateur, critic, editor and active thinker Dr. Sunilkumar Lavate.' },
    synopsis: { mr: 'कोल्हापुरच्या भूमीत वाढलेले, घडलेले डॉ. लवटे — शिक्षक, प्राध्यापक, प्रयोगशील प्राचार्य, स्मृतिसंग्रहालयांचे निर्माते. विविध क्षेत्रांतील त्यांच्या कार्यामुळे कोल्हापूरचे नाव जगभर उंचावले आहे.',
      en: 'Raised and shaped in Kolhapur, Dr. Lavate — teacher, professor, experimental principal, creator of memorial museums — has elevated Kolhapur\u2019s name across the world through his work.' } },
  { id: 5, cover: 'assets/books/vidrohi-tukaram.jpeg', price: '₹25', pages: 24,
    title: { mr: 'विद्रोही संत तुकाराम : जीवन आणि कार्य', en: 'Rebel Saint Tukaram: Life and Work' },
    sub: { mr: 'पुस्तिका', en: 'Booklet' },
    publisher: { mr: 'संवाद प्रकाशन, कोल्हापूर', en: 'Sanvad Prakashan, Kolhapur' },
    release: { mr: '२६ जानेवारी २०२०', en: '26 January 2020' },
    brief: { mr: '\u2018तुकाराम नावाचा संत माणूस\u2019 या ग्रंथाची छोटी प्रतिकृती — कमी वेळात तुकारामांचे नवे रूप समजून घेण्यासाठी.',
      en: 'A brief companion to \u2018Tukaram: The Saint Man\u2019 — understanding Tukaram\u2019s new form in a short read.' },
    synopsis: { mr: 'महाराष्ट्राला संतांची मोठी परंपरा आहे — ज्ञानेश्वर, नामदेव, एकनाथ या परंपरेत संत तुकाराम भागवत धर्माचा कळस ठरले. समाजात समता यावी म्हणून तुकारामांनी क्रांतिकारी निर्णय घेतले; त्यांचा विद्रोह हे त्यांच्या जीवनचरित्राचे ठळक वैशिष्ट्य आहे.',
      en: 'In Maharashtra\u2019s great tradition of saints — Dnyaneshwar, Namdev, Eknath — Tukaram became the pinnacle of Bhagavata Dharma. He made revolutionary decisions for equality; rebellion is the defining feature of his life.' } },
  { id: 6, cover: 'assets/books/hindi.jpeg', price: '₹100', pages: 104,
    title: { mr: 'हिंदी वेब साहित्य', en: 'Hindi Web Literature' },
    sub: { mr: 'संपादित पुस्तिका (हिंदी)', en: 'Edited booklet (Hindi)' },
    publisher: { mr: 'समृद्धि प्रकाशन, कोल्हापूर', en: 'Samriddhi Prakashan, Kolhapur' },
    release: { mr: '१४ नोव्हेंबर २०२०', en: '14 November 2020' },
    brief: { mr: 'हिंदी साहित्याचे ई-स्वरूप, वेबसाइट्स आणि ॲप्स यांची ओळख करून देणारी, जिज्ञासा वाढवणारी संपादित पुस्तिका.',
      en: 'An edited booklet introducing the e-avatar of Hindi literature — its websites and apps — to spark curiosity.' },
    synopsis: { mr: 'इक्कीसवीं सदी का अध्यापक पेन से नहीं, पेनड्राइव से जुडना अनिवार्य है। शिक्षा प्रणाली मौखिक एवं संगणकीय संसाधनों से युक्त होगी तो हम नई मुक्त शिक्षा दे पायेंगे। यह पुस्तिका हमेशा संदर्भ निर्देशिका का काम देगी।',
      en: 'The 21st-century teacher must connect with a pen drive, not just a pen. If education embraces oral and digital resources, we can offer a new, open education — this booklet serves as a lasting reference guide.' } },
];


window.EXTRA = {
  mr: {
    navHome: 'मुखपृष्ठ',
    backHome: '← मुखपृष्ठ',
    viewAllBooks: 'सर्व पुस्तके पहा',
    exploreSamajbhan: 'समाजभान कार्य पहा',
    teaserBooks: 'संविधान, संतसाहित्य, चरित्र आणि समीक्षा — बारा ग्रंथांचा प्रवास.',
    teaserSamaj: 'वंचित व गरजूंसाठी २०१९ पासून ४६ हून अधिक उपक्रम राबवणारा “समाजभान” समूह.',
    samajStats: [
      { num: '४६+', label: 'उपक्रम' },
      { num: '२०१९', label: 'पासून कार्यरत' },
      { num: '६', label: 'कार्यक्षेत्रे' },
    ],
  },
  en: {
    navHome: 'Home',
    backHome: '← Home',
    viewAllBooks: 'View all books',
    exploreSamajbhan: 'Explore Samajbhan',
    teaserBooks: 'The Constitution, saint literature, biography and criticism — a journey of twelve books.',
    teaserSamaj: 'The “Samajbhan” collective — 46+ initiatives for the deprived and needy since 2019.',
    samajStats: [
      { num: '46+', label: 'Initiatives' },
      { num: '2019', label: 'Active since' },
      { num: '6', label: 'Focus areas' },
    ],
  },
};
